# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: php:7.1

# Configuration of the build of the application.
build:
  flavor: composer

# The size of the persistent disk of the application (in MB).
disk: 256

# The mounts that will be performed when the package is deployed.
mounts:
  /web/images: shared:files/images
  /web/cache: shared:files/cache
  /web/logs: shared:files/logs
  /web/tmp: shared:files/tmp
  /web/assets: shared:files/assets
  /web/user/data: shared:files/user/data
  /web/user/config: shared:files/user/config
  /web/backup: shared:files/backup

# The configuration of app when it is exposed to the web.
web:
  locations:
    '/':
      root: 'web'
      passthru: '/index.php'
      expires: 600
      allow: false
      rules:
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true
    /assets:
      root: assets
      scripts: false
      allow: true
      expires: 600
    /images:
      root: images
      scripts: false
      allow: true
      expires: 600

hooks:
  build: |
    cd web
    composer install --no-dev -o
    bin/grav install